package com.kraususa.widgetset;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import data.OrderEntry;

import java.io.IOException;
import java.util.Properties;

import static com.google.common.base.Strings.isNullOrEmpty;

/**
 * The bottom panel to be added at bottom of each page.
 * <p/>
 * Displays version information from the maven build via properties.
 */
@SuppressWarnings("serial")
public class BottomPanel extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

    @AutoGenerated
    private HorizontalLayout mainLayout;
    @AutoGenerated
    private Label label_1;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public BottomPanel() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        Properties props = new Properties();
        try {
            props.load(OrderEntry.class.getClassLoader().getResourceAsStream("buildinfo.properties"));
        } catch (IOException e) {
            e.printStackTrace();
        }

        String version = "Version " + props.getProperty("build.version") +
                " Build at " +
                props.getProperty("build.timestamp");
        if (isNullOrEmpty(version))
            label_1.setValue("UNABLE TO OBTAIN VERSION INFO see log for details.");

        version = version + " \n (C) KrausUSA.com ";
        label_1.setValue(version);

    }

    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("30px");
        mainLayout.setMargin(false);

        // top-level component properties
        setWidth("100.0%");
        setHeight("30px");

        // label_1
        label_1 = new Label();
        label_1.setImmediate(false);
        label_1.setWidth("100.0%");
        label_1.setHeight("100.0%");
        label_1.setValue("BUILD_INFO");
        mainLayout.addComponent(label_1);
        mainLayout.setComponentAlignment(label_1, Alignment.MIDDLE_RIGHT);

        return mainLayout;
    }

}
