package com.kraususa.widgetset;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.*;

public class testComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,7","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":4} */

    @AutoGenerated
    private HorizontalLayout mainLayout;
    @AutoGenerated
    private Link link_2;
    @AutoGenerated
    private Link link_3;
    @AutoGenerated
    private Link link_1;
    @AutoGenerated
    private Embedded logo;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public testComposite() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("80px");
        mainLayout.setMargin(false);

        // top-level component properties
        setWidth("100.0%");
        //setHeight("30.0%");

        // logo
        logo = new Embedded();
        logo.setImmediate(false);
        logo.setWidth("100.0%");
        logo.setHeight("-1px");
        logo.setSource(new ThemeResource("images/40044998v2v1.png"));
        logo.setType(1);
        logo.setMimeType("image/png");
        mainLayout.addComponent(logo);
        mainLayout.setComponentAlignment(logo, new Alignment(33));

        // link_1
        link_1 = new Link();
        link_1.setImmediate(false);
        link_1.setWidth("-1px");
        link_1.setHeight("-1px");
        mainLayout.addComponent(link_1);

        // link_3
        link_3 = new Link();
        link_3.setImmediate(false);
        link_3.setWidth("-1px");
        link_3.setHeight("-1px");
        mainLayout.addComponent(link_3);

        // link_2
        link_2 = new Link();
        link_2.setImmediate(false);
        link_2.setWidth("-1px");
        link_2.setHeight("-1px");
        mainLayout.addComponent(link_2);

        return mainLayout;
    }

}
