package com.kraususa.widgetset;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.*;

public class testComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":4} */

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_1;
    @AutoGenerated
    private Embedded embedded_2;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public testComposite() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // horizontalLayout_1
        horizontalLayout_1 = buildHorizontalLayout_1();
        mainLayout.addComponent(horizontalLayout_1,
                "top:4.0px;right:230.0px;left:0.0px;");

        return mainLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_1() {
        // common part: create layout
        horizontalLayout_1 = new HorizontalLayout();
        horizontalLayout_1.setImmediate(false);
        horizontalLayout_1.setWidth("100.0%");
        horizontalLayout_1.setHeight("100.0%");
        horizontalLayout_1.setMargin(false);

        // embedded_2
        embedded_2 = new Embedded();
        embedded_2.setImmediate(false);
        embedded_2.setWidth("-1px");
        embedded_2.setHeight("-1px");
        embedded_2.setSource(new ThemeResource("img/vaadin-logo.png"));
        embedded_2.setType(1);
        embedded_2.setMimeType("image/png");
        horizontalLayout_1.addComponent(embedded_2);
        horizontalLayout_1.setComponentAlignment(embedded_2, new Alignment(33));

        return horizontalLayout_1;
    }

}
