package com.kraususa.widgetset;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.*;

public class testComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":4} */

    @AutoGenerated
    private AbsoluteLayout mainLayout;
    @AutoGenerated
    private VerticalLayout verticalLayout_1;
    @AutoGenerated
    private HorizontalSplitPanel horizontalSplitPanel_2;
    @AutoGenerated
    private Table table_3;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public testComposite() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("554px");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(false);

        // top-level component properties
        setWidth("554px");
        setHeight("100.0%");

        // verticalLayout_1
        verticalLayout_1 = buildVerticalLayout_1();
        mainLayout.addComponent(verticalLayout_1, "top:30.0px;left:140.0px;");

        return mainLayout;
    }

    @AutoGenerated
    private VerticalLayout buildVerticalLayout_1() {
        // common part: create layout
        verticalLayout_1 = new VerticalLayout();
        verticalLayout_1.setImmediate(false);
        verticalLayout_1.setWidth("-1px");
        verticalLayout_1.setHeight("-1px");
        verticalLayout_1.setMargin(false);
        verticalLayout_1.setSpacing(true);

        // horizontalSplitPanel_2
        horizontalSplitPanel_2 = buildHorizontalSplitPanel_2();
        verticalLayout_1.addComponent(horizontalSplitPanel_2);

        return verticalLayout_1;
    }

    @AutoGenerated
    private HorizontalSplitPanel buildHorizontalSplitPanel_2() {
        // common part: create layout
        horizontalSplitPanel_2 = new HorizontalSplitPanel();
        horizontalSplitPanel_2.setCaption("gdfgdfgdfgh");
        horizontalSplitPanel_2.setImmediate(false);
        horizontalSplitPanel_2.setWidth("100.0%");
        horizontalSplitPanel_2.setHeight("100.0%");
        horizontalSplitPanel_2.setMargin(false);

        // table_3
        table_3 = new Table();
        table_3.setCaption("sdfgsdfgsdfg");
        table_3.setImmediate(false);
        table_3.setWidth("-1px");
        table_3.setHeight("-1px");
        horizontalSplitPanel_2.addComponent(table_3);

        return horizontalSplitPanel_2;
    }

}
