package com.kraususa.widgetset;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.terminal.ThemeResource;
import com.vaadin.ui.*;

public class TopPanel extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,7","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":true,"snappingDistance":4} */

    @AutoGenerated
    private HorizontalLayout mainLayout;
    @AutoGenerated
    private HorizontalLayout horizontalLayout_2;
    @AutoGenerated
    private Link link_log_out;
    @AutoGenerated
    private Embedded logo;

    /**
     * The constructor should first build the main layout, set the
     * composition root and then do any custom initialization.
     * <p/>
     * The constructor will not be automatically regenerated by the
     * visual editor.
     */
    public TopPanel() {
        buildMainLayout();
        setCompositionRoot(mainLayout);

        // TODO add user code here
    }

    @AutoGenerated
    private HorizontalLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new HorizontalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");
        mainLayout.setMargin(true);
        mainLayout.setSpacing(true);

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // logo
        logo = new Embedded();
        logo.setImmediate(false);
        logo.setWidth("30.0%");
        logo.setHeight("100.0%");
        logo.setSource(new ThemeResource("images/40044998v2v1.png"));
        logo.setType(1);
        logo.setMimeType("image/png");
        mainLayout.addComponent(logo);
        mainLayout.setExpandRatio(logo, 4.8f);
        mainLayout.setComponentAlignment(logo, new Alignment(33));

        // horizontalLayout_2
        horizontalLayout_2 = buildHorizontalLayout_2();
        mainLayout.addComponent(horizontalLayout_2);
        mainLayout.setExpandRatio(horizontalLayout_2, 0.6f);
        mainLayout.setComponentAlignment(horizontalLayout_2, new Alignment(34));

        return mainLayout;
    }

    @AutoGenerated
    private HorizontalLayout buildHorizontalLayout_2() {
        // common part: create layout
        horizontalLayout_2 = new HorizontalLayout();
        horizontalLayout_2.setImmediate(false);
        horizontalLayout_2.setWidth("100.0%");
        horizontalLayout_2.setHeight("100.0%");
        horizontalLayout_2.setMargin(false);

        // link_log_out
        link_log_out = new Link();
        link_log_out.setCaption("Log Out");
        link_log_out.setImmediate(false);
        link_log_out.setWidth("-1px");
        link_log_out.setHeight("-1px");
        //link_log_out.addListener();
        horizontalLayout_2.addComponent(link_log_out);

        return horizontalLayout_2;
    }

}
